### ISSUE TITLE
[Log] Reference map 'toyguns.refmap.json' for toyguns.mixins.json could not be read.

### ISSUE THREAD

**Issue by Lucky-56** [Mr-Pineapple/MrPineapplesToyGuns#2]
While starting the game log says `Reference map 'toyguns.refmap.json' for toyguns.mixins.json could not be read. If this is a development environment you can ignore this message`

at startup, assuming I'm not in a 'dev environment' this shouldn't happen

**Comment by Mr-Pineapple** [comment]
Fixed in version 0.3.2
Removed mixins as they aren't needed for anything
