### ISSUE TITLE
Tri Shot multiplies ammo

### ISSUE THREAD

**Issue by NicoTheIdiot** [Mr-Pineapple/MrPineapplesToyGuns#4]
**Using Forge 1.19.2**

When using the Tri Shot,you can duplicate darts.
This happens because when reloading,the gun reloads 4 darts 3 times and fills the 12 dart magazine.
However,instead of shooting 4 times 3 darts,the Tri Shot shoots 12 times 3 darts.
So,if we get the Tri Shot,reload with 12 darts in the inventory and then shoot,we get 36 darts.

_Before reloading:_
![2022-12-25_17 23 01](https://user-images.githubusercontent.com/84082097/209475610-7451d28d-32c8-4591-8cac-235a30fbb1b9.png)

_After reloading:_
![2022-12-25_17 23 12](https://user-images.githubusercontent.com/84082097/209475620-a7f11a12-0bba-41c6-8292-81e3ba564e3b.png)

_After shooting:_
![2022-12-25_17 24 11](https://user-images.githubusercontent.com/84082097/209475624-c4430d36-1451-4503-84e9-e9c4c94a51f1.png)

_After collecting the darts (35 instead of 36 because of dart loss.) :_
![2022-12-25_17 24 24](https://user-images.githubusercontent.com/84082097/209475647-929f43ee-a303-4efb-8820-7a28f8c4c369.png)

**Comment by Mr-Pineapple** [comment]
Fixed in version 0.3.3
https://github.com/Mr-Pineapple/MrPineapplesToyGuns/tree/038eb3161fedc3b372fd86521bb47ad267d89fc8
