### ISSUE TITLE
Unable to play the game even with all requirements.

### ISSUE THREAD

**Issue by TheGlassMan07** [Mr-Pineapple/MrPineapplesToyGuns#5]
_Version: 1.19.2_

Whenever I attempt to boot up the game, I get this error.
![image](https://github.com/user-attachments/assets/b5289abd-dd4c-468a-9cfd-3b31ff3ab157)

Below is my mods folder. **I only have Framework, MrCrayfish's Gun Mod, and the MrPineapple's Toy Guns mod.** I don't get what I'm doing wrong.
![image](https://github.com/user-attachments/assets/f8d555d2-4e54-456d-a3cf-753b3029e498)

**Comment by Mr-Pineapple** [comment]
Fixed in 0.3.2
Issue with updated version of framework where methods had changed
